version: "3.9"

services:
  db:
    image: postgres:15.3-alpine
    ports:
      - 7001:5432
    restart: always
    environment:
      POSTGRES_USER: ourdb
      POSTGRES_PASSWORD: ourpass
      POSTGRES_DB: postgres
